from __future__ import annotations

import hashlib
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path

from .sdk_manager_discovery import SdkManagerDiscovery
from .sdk_manager_role import SdkManagerComponentRole


class SdkManagerResponseFileError(ValueError):
    """Raised when a deterministic SDK Manager response file cannot be built."""


@dataclass(frozen=True, slots=True)
class SdkManagerResponseFile:
    path: Path
    sha256: str
    role_id: str
    role_digest: str


def render_response_file(
    discovery: SdkManagerDiscovery,
    role: SdkManagerComponentRole,
    *,
    download_folder: Path,
) -> str:
    """Render the minimal response file used by Orin Stage acquisition.

    No flash, additional SDK, sudo password or automatic license acceptance is
    inserted. Repeated ``select[]`` entries are kept explicitly because that is
    the format used by NVIDIA's Jetson response-file template.
    """

    folder = Path(download_folder)
    if not folder.is_absolute():
        raise SdkManagerResponseFileError("download folder must be absolute")
    if not role.role_id.strip():
        raise SdkManagerResponseFileError("role id must not be empty")
    if not role.select_groups:
        raise SdkManagerResponseFileError("at least one SDK Manager group is required")
    if role.additional_sdks:
        raise SdkManagerResponseFileError(
            "JP6 core acquisition must not silently include additional SDKs"
        )

    target = discovery.target
    lines = [
        "; Generated by Orin Stage. Do not edit in-place.",
        f"; role-id = {role.role_id}",
        f"; role-digest = {role.digest()}",
        "",
        "[client_arguments]",
        "action = downloadonly",
        "login-type = devzone",
        "product = Jetson",
        f"version = {target.jetpack_version}",
        "target-os = Linux",
    ]

    if role.include_host:
        lines.append("host = true")

    lines.append(f"target = {target.sdk_manager_target}")
    for group in role.select_groups:
        if not group.strip():
            raise SdkManagerResponseFileError("component group must not be empty")
        lines.append(f"select[] = {group}")

    lines.append(f"download-folder = {folder}")
    lines.append("")
    return "\n".join(lines)


def response_file_sha256(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def write_response_file_atomic(
    path: Path,
    content: str,
    *,
    role: SdkManagerComponentRole,
) -> SdkManagerResponseFile:
    """Atomically publish one deterministic response file."""

    path = Path(path)
    if not path.is_absolute():
        raise SdkManagerResponseFileError("response file path must be absolute")

    path.parent.mkdir(parents=True, exist_ok=True)
    digest = response_file_sha256(content)

    fd, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=path.parent,
        text=True,
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)

    return SdkManagerResponseFile(
        path=path,
        sha256=digest,
        role_id=role.role_id,
        role_digest=role.digest(),
    )
